/// Data handling guidance: dates, booleans, editing, statistics.
///
/// Included in every system prompt so the AI knows how to work with
/// module data correctly regardless of the operation.
const dataHandling = 'DATA HANDLING:\n\n'
    'AUTO-GENERATED FIELDS:\n'
    '- id, created_at, and updated_at are auto-set on every entry.\n'
    '- NEVER include these fields in createEntry or createEntries data.\n\n'
    'DATES:\n'
    '- All datetime columns store Unix milliseconds (e.g. 1708819200000).\n'
    '- For user-facing date fields, compute the correct epoch ms from '
    'the user\'s input.\n'
    '- In SQL queries, use strftime for date math:\n'
    '  Today: strftime(\'%s\', date(\'now\')) * 1000\n'
    '  This month: strftime(\'%s\', date(\'now\', \'start of month\')) * 1000\n'
    '  This week: strftime(\'%s\', date(\'now\', \'weekday 0\', \'-6 days\')) * 1000\n\n'
    'BOOLEANS:\n'
    '- Stored as INTEGER: 1 = true, 0 = false.\n\n'
    'CURRENCY:\n'
    '- Currency columns store REAL values in the user\'s main currency '
    '(e.g. 12.50 means \$12.50, not cents).\n'
    '- Always display currency with \$ and two decimal places.\n\n'
    'EDITING ENTRIES:\n'
    '- To edit an entry, ALWAYS queryEntries or runQuery first to find '
    'the entry ID. Never guess an ID.\n'
    '- Ask the user which entry if ambiguous (e.g. "which expense?").\n'
    '- updateEntry does partial merge — only send the fields that changed.\n\n'
    'STATISTICS & ANALYSIS:\n'
    '- Use runQuery for stats, totals, averages, counts, and comparisons.\n'
    '- runQuery supports full SQL: SUM, AVG, COUNT, GROUP BY, date ranges.\n'
    '- Present numbers clearly: format currency with \$, round percentages.\n'
    '- When the user asks "how much", "how many", "what\'s my average", etc. '
    '— use runQuery, don\'t fetch all entries and compute in text.\n\n'
    'ERROR RECOVERY:\n'
    '- If a tool returns an error, read the message carefully.\n'
    '- Common fixes: check column names against the schema, check the '
    'moduleId exists, verify the schemaKey matches.\n'
    '- For SQL errors in runQuery, fix the syntax and retry — don\'t give up.\n'
    '- If you get "Could not resolve table name", use getModuleSummary '
    'first to confirm the module and schema key.';
